export const ALERT="ALERT"
export const REFETCH_CHAT="REFETCH_CHAT"
export const NEW_ATTACHMENT = "NEW_ATTACHMENT";
export const NEW_MESSAGE_ALERT="NEW_MESSAGE_ALERT"
export const NEW_REQUEST = "NEW_REQUEST";